layout_spectrum: 0.9957447
typography_spectrum: 0.6085106
color:
  lightness: 1
  brandStrength: 0.5255319
  saturation: 0.2446809
  rhythmicContrast: 0
  brandColors:
    - '#FEFDFE'
    - '#1E2039'
    - '#91ABCF'
    - '#304B80'
    - '#9A8842'
name: Madeleine Punde Photo
